name: velox
description: Mobile IDE for Android
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.3
  go_router: ^13.2.0
  webview_flutter: ^4.7.0
  webview_flutter_android: ^3.16.0
  shared_preferences: ^2.2.3
  path_provider: ^2.1.3
  path: ^1.9.0
  file_picker: ^8.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  riverpod_generator: ^2.3.9
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/xterm/
    - assets/monaco/
